name: 问题反馈 Bug report
description: 程序出现问题 | Report the error to help lalc improve.
labels: ['bug']
title: "[Bug] Title"
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 应该确定的 | Confirm
      options:
      - label: 已尝试使用搜索引擎，且不能解决我的问题 | I have google it and can hardly find any solution.
        required: true
      - label: 我填写的标题意义明确，而不是“一个建议”、“卡住了”,"LALC无法运行"等 | The title is clear rather than "A advice", "LALC stuck!".
        required: true
      - label:  我已确认目前没有类似 issue | I have confirmed that there is no similar issue at this time. 
        required: true
      - label: 我使用的程序版本已为最新版 | The programme is the latest version.
        required: true
      - label: 我已遵循[指导手册](https://github.com/HSLix/LixAssistantLimbusCompany/blob/master/doc/manual_cn.md)完成相应配置 | I have reviewed the [Manual](https://github.com/HSLix/LixAssistantLimbusCompany/blob/master/doc/manual_en.md)
        required: true
      - label: 我已完整查看过[常见问题](https://github.com/HSLix/LixAssistantLimbusCompany/blob/master/doc/FAQ_cn.md) 部分 | I have reviewed the [FAQ](https://github.com/HSLix/LixAssistantLimbusCompany/blob/master/doc/FAQ_en.md) section
        required: true
      - label: 我理解并愿意跟进此 issue, 协助测试和提供反馈 | I understand and am willing to follow up on this issue, assist with testing and provide feedback.
        required: true
      - label: 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 | I understand and agree with the above, and understand that project maintainers have limited energy, and that issues that don't follow the rules may be ignored or simply shut down
        required: true
  - type: textarea
    id: describe
    attributes:
      label: 问题描述 | Bug Description
      description: 尽可能详细描述你的问题 | Describe the Bug as more details as you can
    validations:
      required: true
  - type: textarea
    id: rebug
    attributes:
      label: 重现问题 | Reproduct the Bug
      description: 在（什么时候），做（什么行为），LALC 出现（什么问题） | 
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: 日志文件 | Log Files (Debug Info Warning Error)
      description: 上传 log 文件夹下当日的所有 log 文件(debug, info, warning, error) | Upload all the log files at that day, including debug, info, warning and error.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 录屏/截图 | Record Video/Screenshot
      description: 上传你发生此问题时的录屏/截图 | Upload the Video/Screenshot when meeting up this Bug.
    validations:
      required: true
  - type: textarea
    id: shouldbe
    attributes:
      label: 应该是？ | Expect Effect
      description: 描述你认为应为的实际效果 | The correct action it should be.
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 其他信息 | Other Information
      description: 操作系统、语言及 LALC 版本号；屏幕分辨率等。| OS, language, Version of LALC, Screen Resolution……
    validations:
      required: false
